const Elevator = require("./elevator.js");
const Person = require("./person.js");

const elevator = new Elevator();
const pers1 = new Person("bob", 3, 7);
const pers2 = new Person("ted", 4, 2);
const pers3 = new Person("cal", 2, 6);
elevator.call(pers1);
elevator.call(pers2);
elevator.call(pers3);
elevator.update();
// elevator.start();
// elevator.floorDown();
// elevator.floorDown();
// elevator.floorDown();
// setTimeout(() => {
//   elevator.stop();
// }, 5000);
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.call(pers1);
// elevator.call(pers2);
// elevator.call(pers3);
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
// elevator.floorUp();
// console.log(elevator.floor);
// elevator._passengersEnter();
// elevator._passengersLeave();
// console.log(elevator.passengers);
// console.log(elevator.waitingList);
// console.log(elevator.requests);
